### PR TITLE
corrected mistake in the original schematic

### PR DESCRIPTION
**Pull request by ugsfume**
Source and drain of P-channel MOSFET Q3 were flipped

### CODE REVIEW

**Comment by frankplow** [comment]
> Are Q1 and Q2 the right way round? Seems a little strange to me that that pair shares the drain terminal while Q3/Q4 share the source terminal. Or is this just because Q1/Q2 switches ground while Q3/Q4 switches +BATT?

Or do Q3 and Q4 both need mirroring? Right now the source terminal of both are floating, so I'm not sure how we get VGS > VGS(th) and turn them on.

**Comment by ugsfume** [comment]
> Are Q1 and Q2 the right way round? Seems a little strange to me that that pair shares the drain terminal while Q3/Q4 share the source terminal. Or is this just because Q1/Q2 switches ground while Q3/Q4 switches +BATT?

Q1 and Q2 pair are NMOSFET whereas Q3 and Q4 pair are PMOSFET

**Comment by frankplow** [comment]
> Or do Q3 and Q4 both need mirroring? Right now the source terminal of both are floating, so I'm not sure how we get VGS > VGS(th) and turn them on.

This point still applies (well, |VGS| > |VGS(th)| to be pedantic), doesn't it?

**Comment by ugsfume** [comment]
The Source net is actually never floating due to the body diodes
IMG_8001

**Comment by ugsfume** [comment]
this configuration is called bidirectional switch if im not wrong

**Review by frankplow — APPROVED** [review]
👍

**Pull request merged**
