### PR TITLE
Pcb

### PR DESCRIPTION
**Pull request by ugsfume**
updated charger IC in both schematic and PCB for JLC basic part

### CODE REVIEW

**Comment by ugsfume** [comment]
battery protection IC not updated, since all are extended parts and the one already on the schematic is the most reputable one

**Comment by ugsfume** [comment]
many neighbouring footprints around MCU are currently overlapped, will update tomorrow.

**Comment by ugsfume** [comment]
imped
just curious, is this for impedence matching?

**Comment by frankplow** [comment]
@ugsfume

I'm not sure we want to merge this branch yet, seeing as we have some major changes left to make.

> many neighbouring footprints around MCU are currently overlapped, will update tomorrow.

I wouldn't worry about this, lots of parts will have to be moved around when I change the MCU and make the board smaller, so I can do this then.

> just curious, is this for impedence matching?

It's for length matching.

**Comment by frankplow** [comment]
@ugsfume Is there any chance we could move 8b6408a and ffea6d5 to a new branch then rebase pcb onto that? Just been fiddling with some bits and it's made the git histories a little awkward. Makes a bit more sense imo as well because the new charger and LDO are primarily changes to the schematic and are not PCB-related.

**Comment by ugsfume** [comment]
moved the changes to a new branch

**Pull request closed without merging**
